name: CSS Validator
on:
  push
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2 # Requried will all actions
        with: 
          ref: feature-tasklist-sync-with-db

      - name: CSS Validator
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: extension/css/
          css: true 