name: HTML Check
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2 # Requried will all actions
        # run: echo ${{ github.repository }}
        with: 
          ref: refactor-dev-cicd
      - name: CSS Validator
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: refactoring/css/
          css: true 