name: HTML5 Validator
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "$GITHUB_WORKSPACE"
    - name: Checkout repo 
      uses: actions/checkout@v2 # Requried will all actions

      with: 
        ref: feature-tasklist-sync-with-db
    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: extension/
 
  